"""Add looking for and contact to user table make sensor based fields nullable

Revision ID: 2657b9fd06d1
Revises: fc7c7c96fd3d
Create Date: 2018-09-01 12:52:15.207304

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '2657b9fd06d1'
down_revision = 'fc7c7c96fd3d'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('login_user', sa.Column('contact', sa.String(), nullable=False))
    op.add_column('login_user', sa.Column('looking_for', sa.String(), nullable=False))
    op.alter_column('login_user', 'humidity',
               existing_type=sa.NUMERIC(),
               nullable=True)
    op.alter_column('login_user', 'magnetic_flux',
               existing_type=sa.NUMERIC(),
               nullable=True)
    op.alter_column('login_user', 'temperature',
               existing_type=sa.NUMERIC(),
               nullable=True)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('login_user', 'temperature',
               existing_type=sa.NUMERIC(),
               nullable=False)
    op.alter_column('login_user', 'magnetic_flux',
               existing_type=sa.NUMERIC(),
               nullable=False)
    op.alter_column('login_user', 'humidity',
               existing_type=sa.NUMERIC(),
               nullable=False)
    op.drop_column('login_user', 'looking_for')
    op.drop_column('login_user', 'contact')
    # ### end Alembic commands ###
