"""Add match table

Revision ID: 26ddb86173a0
Revises: 882016079b4a
Create Date: 2018-09-01 17:51:32.636144

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '26ddb86173a0'
down_revision = '882016079b4a'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('match',
    sa.Column('match_id', sa.Integer(), nullable=False),
    sa.Column('user_1', sa.Integer(), nullable=False),
    sa.Column('user_2', sa.Integer(), nullable=False),
    sa.Column('status', sa.String(), nullable=False),
    sa.CheckConstraint("status in ('matched', 'not_matched')", name='check_match_status'),
    sa.ForeignKeyConstraint(['user_1'], ['login_user.login_user_id'], ),
    sa.ForeignKeyConstraint(['user_2'], ['login_user.login_user_id'], ),
    sa.PrimaryKeyConstraint('match_id'),
    sa.UniqueConstraint('user_1', 'user_2', name='matches_unique_constraint')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('match')
    # ### end Alembic commands ###
