"""Make user col non unique, and new unique col for IMEI

Revision ID: 882016079b4a
Revises: 2657b9fd06d1
Create Date: 2018-09-01 13:35:38.353797

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '882016079b4a'
down_revision = '2657b9fd06d1'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('login_user', sa.Column('unique_identifier', sa.String(), nullable=False))
    op.drop_constraint('login_user_username_key', 'login_user', type_='unique')
    op.create_unique_constraint(None, 'login_user', ['unique_identifier'])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'login_user', type_='unique')
    op.create_unique_constraint('login_user_username_key', 'login_user', ['username'])
    op.drop_column('login_user', 'unique_identifier')
    # ### end Alembic commands ###
