"""User table for tinder for EMF

Revision ID: fc7c7c96fd3d
Revises: a3f24e3fc622
Create Date: 2018-09-01 12:44:58.841899

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = 'fc7c7c96fd3d'
down_revision = 'a3f24e3fc622'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('submitted_result')
    op.drop_table('request_token')
    op.add_column('login_user', sa.Column('age', sa.Integer(), nullable=False))
    op.add_column('login_user', sa.Column('humidity', sa.Numeric(), nullable=False))
    op.add_column('login_user', sa.Column('magnetic_flux', sa.Numeric(), nullable=False))
    op.add_column('login_user', sa.Column('tag_line', sa.String(), nullable=False))
    op.add_column('login_user', sa.Column('temperature', sa.Numeric(), nullable=False))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('login_user', 'temperature')
    op.drop_column('login_user', 'tag_line')
    op.drop_column('login_user', 'magnetic_flux')
    op.drop_column('login_user', 'humidity')
    op.drop_column('login_user', 'age')
    op.create_table('request_token',
    sa.Column('request_token_id', sa.INTEGER(), server_default=sa.text("nextval('request_token_request_token_id_seq'::regclass)"), nullable=False),
    sa.Column('user_id', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('request_token', sa.VARCHAR(), autoincrement=False, nullable=False),
    sa.Column('requested_at', postgresql.TIMESTAMP(timezone=True), server_default=sa.text('now()'), autoincrement=False, nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['login_user.login_user_id'], name='request_token_user_id_fkey'),
    sa.PrimaryKeyConstraint('request_token_id', name='request_token_pkey'),
    sa.UniqueConstraint('request_token', name='request_token_request_token_key'),
    postgresql_ignore_search_path=False
    )
    op.create_table('submitted_result',
    sa.Column('submitted_result_id', sa.INTEGER(), nullable=False),
    sa.Column('request_token_id', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('result_value', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.ForeignKeyConstraint(['request_token_id'], ['request_token.request_token_id'], name='submitted_result_request_token_id_fkey'),
    sa.PrimaryKeyConstraint('submitted_result_id', name='submitted_result_pkey')
    )
    # ### end Alembic commands ###
